
package net.myorb.rpc.interpreters;

import net.myorb.data.notations.json.JsonReader;
import net.myorb.data.notations.json.JsonSemantics;

import net.myorb.data.abstractions.SimpleStreamIO.TextSource;

import java.io.StringReader;

/**
 * parse JSON text used in communications
 * @author Michael Druckman
 */
public class JsonInterpreter
{

	/**
	 * process a JSON request packet
	 * @param request the text string assumed to be JSON source
	 * @return the response generated by the JSON processor
	 * @throws Exception for JSON parser errors
	 */
	public JsonSemantics.JsonValue interpret (String request) throws Exception
	{
		return read (new TextSource (new StringReader (request)));
	}

	/**
	 * @param source a text source for the request
	 * @return the JSON expression tree read by the parser
	 * @throws Exception for JSON parser errors
	 */
	public JsonSemantics.JsonValue read (TextSource source) throws Exception
	{
		return JsonReader.readFrom (source);
	}

}
